### ISSUE TITLE
[Enhancement]: 

### ISSUE THREAD

**Issue by harshil4076** [polyseam/cndi#496] opened 2023-09-03 13:01 UTC
### Version

1.13.3

### Please provide a summary of the enhancement you are proposing:

Option to not sync/delete resources from a resource groups. 

### Please provide the motivation or use case for this enhancement:

Many organizations use their resource groups for multiple purposes.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by johnstonmatt** [comment] 2023-09-06 19:10
closing this as a duplicate of  #499

**Closed as completed by johnstonmatt** 2023-09-06 19:10 UTC
Labels: duplicate, enhancement
